// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Football_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class Football_DetailViewModel : ViewModelsBase.VMBase, IViewModels.IFootball_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.Football_Football _football_Football;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Football_DetailViewModel" /> class.
        /// </summary>
        /// <param name="football_Football">The Football_ Football.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public Football_DetailViewModel(Repositories.Football_Football football_Football, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_football_Football = football_Football;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private Entities.FootballSchema _currentFootballSchema;

        /// <summary>
        /// CurrentFootballSchema property.
        /// </summary>		
        public Entities.FootballSchema CurrentFootballSchema
        {
            get
            {
				return _currentFootballSchema;
            }
            set
            {
                SetProperty(ref _currentFootballSchema, value);
            }
        }
	
		private bool _hasNextpanoramaFootball_Detail0;

        /// <summary>
        /// HasNextpanoramaFootball_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaFootball_Detail0
        {
            get
            {
				return _hasNextpanoramaFootball_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaFootball_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaFootball_Detail0;

        /// <summary>
        /// HasPreviouspanoramaFootball_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaFootball_Detail0
        {
            get
            {
				return _hasPreviouspanoramaFootball_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaFootball_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechFootball_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechFootball_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentFootballSchema.Subtitle + " " + CurrentFootballSchema.Description);
        }
		

        private ICommand _textToSpeechFootball_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechFootball_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechFootball_DetailStaticControlCommand
        {
            get { return _textToSpeechFootball_DetailStaticControlCommand = _textToSpeechFootball_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechFootball_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareFootball_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareFootball_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentFootballSchema.Subtitle, CurrentFootballSchema.Description, "", CurrentFootballSchema.Image);
        }
		

        private ICommand _shareFootball_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareFootball_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareFootball_DetailStaticControlCommand
        {
            get { return _shareFootball_DetailStaticControlCommand = _shareFootball_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareFootball_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartFootball_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartFootball_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.IFootball_DetailViewModel), CreateTileInfoFootball_DetailStaticControl());
        }
		

        private ICommand _pinToStartFootball_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartFootball_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartFootball_DetailStaticControlCommand
        {
            get { return _pinToStartFootball_DetailStaticControlCommand = _pinToStartFootball_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartFootball_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the NextpanoramaFootball_Detail0 command.
        /// </summary>
        public  void NextpanoramaFootball_Detail0Delegate() 
        {
			var next =  _football_Football.Next(CurrentFootballSchema);

			if(next != null)
				CurrentFootballSchema = next;

			RefreshHasPrevNext();
        }
		

        private ICommand _nextpanoramaFootball_Detail0;

        /// <summary>
        /// Gets the NextpanoramaFootball_Detail0 command.
        /// </summary>
        public ICommand NextpanoramaFootball_Detail0
        {
            get { return _nextpanoramaFootball_Detail0 = _nextpanoramaFootball_Detail0 ?? new ViewModelsBase.DelegateCommand(NextpanoramaFootball_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the PreviouspanoramaFootball_Detail0 command.
        /// </summary>
        public  void PreviouspanoramaFootball_Detail0Delegate() 
        {
			var prev =  _football_Football.Previous(CurrentFootballSchema);

			if(prev != null)
				CurrentFootballSchema = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaFootball_Detail0;

        /// <summary>
        /// Gets the PreviouspanoramaFootball_Detail0 command.
        /// </summary>
        public ICommand PreviouspanoramaFootball_Detail0
        {
            get { return _previouspanoramaFootball_Detail0 = _previouspanoramaFootball_Detail0 ?? new ViewModelsBase.DelegateCommand(PreviouspanoramaFootball_Detail0Delegate); }
        }

        private void RefreshHasPrevNext()
        {
            HasPreviouspanoramaFootball_Detail0 = _football_Football.HasPrevious(CurrentFootballSchema);
			HasNextpanoramaFootball_Detail0 = _football_Football.HasNext(CurrentFootballSchema);
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is Entities.FootballSchema)) { return; }
                
                CurrentFootballSchema = value as Entities.FootballSchema;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the Football_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoFootball_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentFootballSchema.Id.ToString(),
                Title = CurrentFootballSchema.Subtitle,
                BackTitle = CurrentFootballSchema.Subtitle,
                BackContent = CurrentFootballSchema.Description,
                Count = 0,
                BackgroundImagePath = CurrentFootballSchema.Image,
                BackBackgroundImagePath = CurrentFootballSchema.Image,
                LogoPath = "Item-3971bce7-d5b3-4c23-b180-7cba99540ee8.png"
            };
            return tileInfo;
        }
    }
}
