// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Football_List ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class Football_ListViewModel : ViewModelsBase.VMBase, IViewModels.IFootball_ListViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ILockScreenService _lockScreenService;
		private readonly Repositories.IFootball_Football _football_Football;
		private readonly IServices.IInternetService _internetService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Football_ListViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="lockScreenService">The Lock Screen Service.</param>
        /// <param name="football_Football">The Football_ Football.</param>
        /// <param name="internetService">The Internet Service.</param>
        public Football_ListViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ILockScreenService lockScreenService, Repositories.IFootball_Football football_Football, IServices.IInternetService internetService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_lockScreenService = lockScreenService;
			_football_Football = football_Football;
			_internetService = internetService;
        }
		
	    /// <summary>
        /// IsInternetAvalaible property.
        /// </summary>		
        public Visibility IsInternetAvalaible
        {
	      get
          {
				return _internetService.IsNetworkAvailable() ? Visibility.Collapsed : Visibility.Visible; 
           }
		}
	
		private ObservableCollection<Entities.FootballSchema> _football_ListListControlCollection;

        /// <summary>
        /// Football_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.FootballSchema> Football_ListListControlCollection
        {
            get
            {
				
                if(_football_ListListControlCollection == null)
					_football_ListListControlCollection = _football_Football.GetData();
				return _football_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _football_ListListControlCollection, value);
            }
        }
	
		private int _football_ListListControlCollectionPageNumber;

        /// <summary>
        /// Football_ListListControlCollectionPageNumber property.
        /// </summary>		
        public int Football_ListListControlCollectionPageNumber
        {
            get
            {
				return _football_ListListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _football_ListListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.FootballSchema _selectedFootball_ListListControlCollection;

        /// <summary>
        /// SelectedFootball_ListListControlCollection property.
        /// </summary>		
        public Entities.FootballSchema SelectedFootball_ListListControlCollection
        {
            get
            {
				return _selectedFootball_ListListControlCollection;
            }
            set
            {
                _selectedFootball_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.IFootball_DetailViewModel>(_selectedFootball_ListListControlCollection);
            }
        }

        /// <summary>
        /// Delegate method for the GetFootball_ListListControlCollectionCommand command.
        /// </summary>
        public  void GetFootball_ListListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				GetFootball_ListListControlCollectionData(pageNumber);
        }
		

        private ICommand _getFootball_ListListControlCollectionCommand;

        /// <summary>
        /// Gets the GetFootball_ListListControlCollectionCommand command.
        /// </summary>
        public ICommand GetFootball_ListListControlCollectionCommand
        {
            get { return _getFootball_ListListControlCollectionCommand = _getFootball_ListListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(GetFootball_ListListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the SetLockScreenCommand command.
        /// </summary>
        public  void SetLockScreenCommandDelegate() 
        {
				_lockScreenService.SetLockScreen("DoWapp-Splashscreen-WXGA-black.png");
        }
		

        private ICommand _setLockScreenCommand;

        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
        public ICommand SetLockScreenCommand
        {
            get { return _setLockScreenCommand = _setLockScreenCommand ?? new ViewModelsBase.DelegateCommand(SetLockScreenCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the AboutCommand command.
        /// </summary>
        public  void AboutCommandDelegate() 
        {
				_navigationService.NavigateTo<IViewModels.IAboutViewModel>();
        }
		

        private ICommand _aboutCommand;

        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
        public ICommand AboutCommand
        {
            get { return _aboutCommand = _aboutCommand ?? new ViewModelsBase.DelegateCommand(AboutCommandDelegate); }
        }

        private void GetFootball_ListListControlCollectionData(int pageNumber = 0)
        {
				Football_ListListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _football_Football.GetData(pageNumber);
                    Football_ListListControlCollection = items;
				}
                else   
				{
					var items = _football_Football.GetData(pageNumber);
                    foreach (var item in items)                    
                        Football_ListListControlCollection.Add(item);
				}
		}
    }
}
