// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Football_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IFootball_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentFootballSchema property.
        /// </summary>
		Entities.FootballSchema CurrentFootballSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaFootball_Detail0 property.
        /// </summary>
		bool HasNextpanoramaFootball_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaFootball_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaFootball_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechFootball_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechFootball_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareFootball_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareFootball_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartFootball_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartFootball_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaFootball_Detail0 command.
        /// </summary>
		ICommand NextpanoramaFootball_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaFootball_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaFootball_Detail0 { get; }

	}
}
